name: Deploy Site to GitHub pages

on:
  push:
    branch: main

job:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: npx @11ty/eleventy
        environment: |
          URL = https://spaenleh.github.io/blog

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          name: blog
          path: dist

  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
        with:
          artifact_name: blog
